// Mocks generated by Mockito 5.0.10 from annotations
// in news_flutter_app/test/viewmodel/top_headline_viewmodel_bloc_mock_mokito_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_flutter_app/model/response/fetch_list_article_response.dart'
    as _i2;
import 'package:news_flutter_app/repository/news_service.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeFetchListArticleResponse extends _i1.Fake
    implements _i2.FetchListArticleResponse {}

/// A class which mocks [NewsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsService extends _i1.Mock implements _i3.NewsService {
  MockNewsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(Invocation.getter(#apiKey), returnValue: '')
          as String);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  _i4.Future<_i2.FetchListArticleResponse> fetchArticles(
          {String? keyword, int? page, int? pageSize}) =>
      (super.noSuchMethod(
              Invocation.method(#fetchArticles, [],
                  {#keyword: keyword, #page: page, #pageSize: pageSize}),
              returnValue: Future<_i2.FetchListArticleResponse>.value(
                  _FakeFetchListArticleResponse()))
          as _i4.Future<_i2.FetchListArticleResponse>);
  @override
  _i4.Future<_i2.FetchListArticleResponse> fetchTopHeadlines(
          {int? page, int? pageSize}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #fetchTopHeadlines, [], {#page: page, #pageSize: pageSize}),
              returnValue: Future<_i2.FetchListArticleResponse>.value(
                  _FakeFetchListArticleResponse()))
          as _i4.Future<_i2.FetchListArticleResponse>);
}
